# fly.toml app configuration file generated for one-piece-api on 2023-06-10T09:24:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "one-piece-api"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
